feat(task): Реализация сервиса управления сделками.
ChiniakinD/deal pull request #1
Opened 2024-07-23 08:41 UTC by ChiniakinD

2024-07-23 13:23 UTC, gobaz095 requested changes
Ну и тестов не хватает:)

2024-07-23 13:23 UTC, gobaz095 commented on src/test/java/com/chiniakin/TestBeans.java
Погаси контейнер с БД и попробуй запустить тесты:)
Тесты должны запускаться без доп настроек. Максимум требуется доп окружение в виде докера. Самого докреа, а не запущенного контрейнера.
Если тестам требуется БД, то они должны сами поднять докер контейнер настроенный.

2024-07-23 13:23 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ScheduledService.java
Тесты

2024-07-23 13:23 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ScheduledService.java
> +        for (OutboxMessage outboxMessage : errorTasks) {
а что если у меня у меня есть 3 изменения статуса:
1 false успешно
2 true ошибка
3 false успешно
Получается актуальный статус = false, а мы отправим дополнительно true

2024-07-23 13:23 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/DealServiceImpl.java
> +        if (dealContractorRepository.checkMain(mainContractor.getContractorId()) == 1) {
Если у контрагента одна сделка где он основной заемщик, то ты отправляешь true. Если меняется статус с DRAFT на ACTIVE. А что если меняется с CLOSED на ACTIVE? А что если у него есть еще одна закрытая сделка? А это новая? 
Иначе фолс, если статус сменился на closed.
Но мы же можем закрыть одну сделку, а у него останутся еще две или более активных и мы отправил false?

2024-07-23 21:18 UTC, ChiniakinD commented on src/test/java/com/chiniakin/TestBeans.java
Я посмотрел, у меня без контейнера с БД работает или это я что-то не понимаю)
![1](https://github.com/user-attachments/assets/13f52b20-0cc4-433e-8025-a0cea28d0147)
![2](https://github.com/user-attachments/assets/fd85b19f-c078-4b3f-ad77-2d6a4cf2fa4a)

2024-07-23 21:19 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/ScheduledService.java
> +        for (OutboxMessage outboxMessage : errorTasks) {
[9ebfbb4](https://github.com/ChiniakinD/deal/pull/1/commits/9ebfbb47c6328f25125399ff7a98318c5b700536)

2024-07-23 21:20 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/DealServiceImpl.java
> +        if (dealContractorRepository.checkMain(mainContractor.getContractorId()) == 1) {
[4ff6e73](https://github.com/ChiniakinD/deal/pull/1/commits/4ff6e737b239133cb63b2f6f2f3f3608a1062ef2)

2024-07-24 13:28 UTC, gobaz095 commented on src/test/java/com/chiniakin/TestBeans.java
Да, увидел теперь, но у тебя падают тесты теперь:
[ERROR]   ContractorRoleRepositoryTest.shouldReturnAllRolesForDealContractorId:30 expected: <1> but was: <0>
[ERROR]   DealContractorRepositoryTest.shouldReturnAllActiveContractorsForDealId:39 expected: <false> but was: <true>
[ERROR]   DealContractorRepositoryTest.shouldReturnCorrectMainContractorForDealId:48 expected: not <null>
[ERROR]   DealContractorRepositoryTest.shouldReturnTrueIfMainContractorExistsForDealId:33 expected: <true> but was: <false>

2024-07-24 13:28 UTC, gobaz095 commented on src/main/java/com/chiniakin/repository/ContractorRoleRepository.java
> +            "where cr.id = (select ctr.role_id from contractor_to_role ctr where ctr.contractor_id = :dealId)", nativeQuery = true)
Что то мне подсказывает, что тут ошибка:)

2024-07-24 13:37 UTC, gobaz095 requested changes

2024-07-24 13:37 UTC, gobaz095 commented on src/test/java/com/chiniakin/controller/ContractorToRoleControllerTest.java
> +public class ContractorToRoleControllerTest {
public в тестах не обязателен, попробуй изучить вопрос почему

2024-07-24 13:37 UTC, gobaz095 commented on src/main/java/com/chiniakin/mapper/DealContractorMapper.java
> +                .collect(Collectors.toList()) : new ArrayList<>();
а можно просто stream.toList()

2024-07-24 13:37 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/DealServiceImpl.java
> +            if (deal.getStatus().getId().equals("DRAFT") && changeStatusModel.getDealStatusId().equals("ACTIVE")) {
Напрашивается Enum для статусов

2024-07-25 07:35 UTC, gobaz095 commented on src/main/java/com/chiniakin/repository/ContractorRoleRepository.java
> +            "where cr.id = (select ctr.role_id from contractor_to_role ctr where ctr.contractor_id = :dealId)", nativeQuery = true)
Или неправильный нейминг, передаешь dealId, а ищешь по contractor_id

2024-07-25 14:41 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/DealServiceImpl.java
> +            if (deal.getStatus().getId().equals("DRAFT") && changeStatusModel.getDealStatusId().equals("ACTIVE")) {
https://github.com/ChiniakinD/deal/pull/1/commits/7a5d1315a739c7f64572fa820fd35ebb5ef6df77

2024-07-25 14:42 UTC, ChiniakinD commented on src/main/java/com/chiniakin/mapper/DealContractorMapper.java
> +                .collect(Collectors.toList()) : new ArrayList<>();
https://github.com/ChiniakinD/deal/pull/1/commits/b14accce1959b8a7dd0e724fb13d7eda15949ef2

2024-07-25 14:42 UTC, ChiniakinD commented on src/main/java/com/chiniakin/repository/ContractorRoleRepository.java
> +            "where cr.id = (select ctr.role_id from contractor_to_role ctr where ctr.contractor_id = :dealId)", nativeQuery = true)
https://github.com/ChiniakinD/deal/pull/1/commits/b17bce5a6154a2748e90f253aa9fab4b62d7ac25

2024-07-25 14:42 UTC, ChiniakinD commented on src/test/java/com/chiniakin/TestBeans.java
https://github.com/ChiniakinD/deal/pull/1/commits/da2a3aec7e9f0349f843d02e5e485f69a9b5369b

2024-07-26 04:38 UTC, ChiniakinD commented on src/test/java/com/chiniakin/controller/ContractorToRoleControllerTest.java
> +public class ContractorToRoleControllerTest {
Изучил, убрал

2024-07-26 09:48 UTC, gobaz095 approved these changes
Норм, можно слить

2024-07-26 11:46 UTC, merged