feat(): Добавление auth
ChiniakinD/deal pull request #2
Opened 2024-08-04 17:38 UTC by ChiniakinD

1. Поменял порты.
2. Добавил ключ для токена.
3. Добавил необходимость авторизации и разграничил права на пользование в завимости от роли пользователя.

2024-08-07 09:12 UTC, gobaz095 requested changes
В тестах скачат public и package-private
Плюс отсутствуют сами тесты на секьюрность

2024-08-07 09:12 UTC, gobaz095 commented on src/main/java/com/chiniakin/controller/DealController.java
> +    @PreAuthorize("hasAnyAuthority('CREDIT_USER', 'OVERDRAFT_USER', 'DEAL_SUPERUSER', 'SUPERUSER')")
Константы для ролей

2024-08-07 09:12 UTC, gobaz095 commented on src/main/java/com/chiniakin/config/auth/SecurityConfig.java
> +        auth.userDetailsService(userDetailsService);
PasswordEncoder лучше хотя бы bcrypt

2024-08-07 09:12 UTC, gobaz095 commented on src/main/java/com/chiniakin/config/auth/SecurityConfig.java
> +@EnableGlobalMethodSecurity(prePostEnabled = true)
EnableGlobalMethodSecurity - deprecated

2024-08-07 09:12 UTC, gobaz095 commented on src/main/java/com/chiniakin/config/auth/SecurityConfig.java
> +                .httpBasic(httpBasic -> httpBasic.disable())
Просто напоминание: AbstractHttpConfigurer::disable можно еще так

2024-08-07 09:12 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/DealServiceImpl.java
> +        Page<Deal> deals = dealRepository.findAll(DealServiceSpecification.buildSpecification(dealFilter, SecurityUtil.getUserRoles()), pageable);
немного сложный вызов, лучше все же findAll(filter) а уже внутри весь этот разбор

2024-08-11 19:50 UTC, ChiniakinD commented on src/main/java/com/chiniakin/config/auth/SecurityConfig.java
> +@EnableGlobalMethodSecurity(prePostEnabled = true)
https://github.com/ChiniakinD/deal/pull/2/commits/d998ffc5869f122aabda54492d8c7e88b683b4ce

2024-08-11 19:50 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/DealServiceImpl.java
> +        Page<Deal> deals = dealRepository.findAll(DealServiceSpecification.buildSpecification(dealFilter, SecurityUtil.getUserRoles()), pageable);
https://github.com/ChiniakinD/deal/pull/2/commits/ed64e9e4f167ec74ad3e96897c6fc7afc98cefce

2024-08-11 19:51 UTC, ChiniakinD commented on src/main/java/com/chiniakin/controller/DealController.java
> +    @PreAuthorize("hasAnyAuthority('CREDIT_USER', 'OVERDRAFT_USER', 'DEAL_SUPERUSER', 'SUPERUSER')")
https://github.com/ChiniakinD/deal/pull/2/commits/c5708bf6036f6b73d6246a769b889faac7ff60f7

2024-08-11 19:53 UTC, ChiniakinD commented on src/main/java/com/chiniakin/config/auth/SecurityConfig.java
> +        auth.userDetailsService(userDetailsService);
![Bcrypt](https://github.com/user-attachments/assets/aabb5fcd-ba3a-4f93-af29-f606ebaaa595)

2024-08-19 18:03 UTC, gobaz095 approved these changes
Жаль что все же без отдельной либы. Но можно сливать.

2024-08-21 05:12 UTC, merged